export const env = {
  RAZORPAY_SECRET_KEY_ID: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET: process.env.NEXT_PUBLIC_RAZORPAY_KEY_SECRET,
  DEFAULT_CUSTOMER_EMAIL: process.env.NEXT_PUBLIC_DEFAULT_RAZORPAY_CUSTOMER_EMAIL,
  RAZORPAY_CHECKOUT_URL: process.env.NEXT_RAZORPAY_CHECKOUT_URL,
};
